/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author yoselin
 */
public class ViewOperaciones extends javax.swing.JFrame {

    /**
     * Creates new form ViewOperaciones
     */
    public ViewOperaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jtf_numero1 = new javax.swing.JTextField();
        Jtf_resultado = new javax.swing.JTextField();
        Jtf_numero2 = new javax.swing.JTextField();
        Jl_numero1 = new javax.swing.JLabel();
        Jl_numero2 = new javax.swing.JLabel();
        Jl_resultado = new javax.swing.JLabel();
        Jb_resta = new javax.swing.JButton();
        Jb_multiplicacion = new javax.swing.JButton();
        Jb_divicion = new javax.swing.JButton();
        Jb_modulo = new javax.swing.JButton();
        Jb_suma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 48)); // NOI18N
        jLabel1.setText("Calculadora ");

        Jtf_numero1.setText(" ");

        Jtf_resultado.setText(" ");
        Jtf_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_resultadoActionPerformed(evt);
            }
        });

        Jtf_numero2.setText(" ");

        Jl_numero1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Jl_numero1.setText("Número1:");

        Jl_numero2.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Jl_numero2.setText("Número2:");

        Jl_resultado.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Jl_resultado.setText("Resultado:");

        Jb_resta.setBackground(new java.awt.Color(255, 255, 255));
        Jb_resta.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Jb_resta.setText("Resta");

        Jb_multiplicacion.setBackground(new java.awt.Color(255, 255, 255));
        Jb_multiplicacion.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Jb_multiplicacion.setText("Multiplicacion");

        Jb_divicion.setBackground(new java.awt.Color(255, 255, 255));
        Jb_divicion.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Jb_divicion.setText("Divicion");

        Jb_modulo.setBackground(new java.awt.Color(255, 255, 255));
        Jb_modulo.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Jb_modulo.setText("Modulo");

        Jb_suma.setBackground(new java.awt.Color(255, 255, 255));
        Jb_suma.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Jb_suma.setText("Suma");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Jb_divicion)
                        .addGap(37, 37, 37)
                        .addComponent(Jb_modulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jb_suma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jb_resta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jb_multiplicacion)))
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Jl_numero2)
                        .addComponent(Jl_numero1))
                    .addComponent(Jl_resultado))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jtf_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_numero1)
                    .addComponent(Jtf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_numero2)
                    .addComponent(Jtf_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_resultado)
                    .addComponent(Jtf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jb_suma)
                    .addComponent(Jb_resta)
                    .addComponent(Jb_multiplicacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jb_divicion)
                    .addComponent(Jb_modulo))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtf_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Jb_divicion;
    public javax.swing.JButton Jb_modulo;
    public javax.swing.JButton Jb_multiplicacion;
    public javax.swing.JButton Jb_resta;
    public javax.swing.JButton Jb_suma;
    public javax.swing.JLabel Jl_numero1;
    public javax.swing.JLabel Jl_numero2;
    public javax.swing.JLabel Jl_resultado;
    public javax.swing.JTextField Jtf_numero1;
    public javax.swing.JTextField Jtf_numero2;
    public javax.swing.JTextField Jtf_resultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
